# Generated by Django 4.2 on 2025-05-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(blank=True, null=True)),
                ('mark', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('generation_name', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.IntegerField()),
                ('mileage', models.IntegerField()),
                ('vol_engine', models.FloatField()),
                ('fuel', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
